__title__ = 'broccoli'
__description__ = 'Framework for game creation by Python/Tkinter.'
__url__ = 'https://github.com/naritotakizawa/broccoli/'
__version__ = '0.2.3'
__author__ = 'Narito Takizawa'
__author_email__ = 'toritoritorina@gmail.com'
__license__ = 'MIT License'
__copyright__ = 'Copyright 2018 Narito Takizawa'
