__title__ = 'broccoli'
__description__ = 'Python/Tkinterでの2Dゲーム作成を支援するフレームワーク'
__url__ = 'https://github.com/naritotakizawa/broccoli/'
__version__ = '1.0.0'
__author__ = 'Narito Takizawa'
__author_email__ = 'toritoritorina@gmail.com'
__license__ = 'MIT License'
__copyright__ = 'Copyright 2018 Narito Takizawa'
